### ISSUE TITLE
Pandas ValueError: operands could not be broadcast together with shapes (3,) (6,)

### ISSUE THREAD

**Issue by dkingram** [aws-samples/sagemaker-serverless-inference-benchmarking#1]
@szamarin Thank you for this very useful toolkit! It has already helped me verify some SageMaker Serverless Inference deployments. In some cases it is useful to execute `run_serverless_benchmarks()` with fewer than the full 6 memory size options. For example, when I tried this: `memory_sizes=[4096, 5120, 6144]` it would throw an exception from Pandas:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1108474/202868111-a32d6c77-ff4a-48a6-a333-1339c66a3106.png">

The problem originated here due to the hard-coded "6" in Line #318 of `analysis.py`:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1108474/202867994-f5280f42-3340-4943-83c4-76c677cce01a.png">

This one-line change at Line #318 in `analysis.py` fixed the issue for running with 1-5 memory sizes:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1108474/202868019-ee922600-960b-45a7-b47d-9e5871493a57.png">

Thanks again for a great piece of work!

**Comment by szamarin** [comment]
Thanks for pointing this out @dkingram! I've released a new version which fixes this. Glad you're finding the tool useful and really appreciate your feedback.

**Comment by szamarin** [comment]
Fixed in 0.2.2
